title = "Indmind Blog"
baseURL = "https://indmind.github.io/blog/"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "UA-112637824-1"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "indmindBlog"

publishDir = "docs"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Indmind"
  description = "Indmind Personal Blog"
  keywords = "blog,personal"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Hello World! Welcome to my personal Blog!"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "https://avatars2.githubusercontent.com/u/29256127?s=460&v=4"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

  # social media profile urls for the footer links
  facebook   = ""
  twitter    = "https://twitter.com/dieorcrypt"
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/indmind"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
